# Generated by Django 4.0.2 on 2022-02-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=255, verbose_name='URL')),
                ('note', models.TextField(default='', verbose_name='Note')),
            ],
        ),
    ]
